### ISSUE TITLE
Feature request: Allow specifying component-specific max trace levels

### ISSUE THREAD

**Issue by teetak01** [PelionIoT/mbed-trace#59]
Something like this might be nice for trace-optimization.

You could choose what level of tracing you care from any component/group and anything extra is not compiled in code.

For ex. something like:

mbed_trace_max_trace_level(TEST, DEBUG);
mbed_trace_max_trace_level(MAIN, WARN);

**Comment by teetak01** [comment]
This could be also used to disable tracing from specific components.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-1914

**Comment by jupe** [comment]
@tommikas do you have time for this?

**Comment by jupe** [comment]
compiling time or runtime ? runtime is quite easy but compiling time is more complicated...

**Comment by teetak01** [comment]
I think we want it to be compile-time with the goal of saving flash from such components we don't care about.

**Comment by teetak01** [comment]
But functionally, the application should have the capability to control tracing from all the dependencies as override.

**Comment by tommikas** [comment]
> @tommikas do you have time for this?

Not really right now.

> We already have this (#53), but I think this will affect all the components?

Yes, although that macro could be set in the source files just before including "mbed_trace.h" to set max level for specific files. You could do that conditionally based on self-defined macros to create groups.

>the application should have the capability to control tracing from all the dependencies as override

This could be also done like that, but it'd require the component to have explicit support for it. Basically a component specific "enable traces" flag.
